## POKEMONS :D

In [1]:
import requests
import pandas as pd

In [2]:
url = "https://pokeapi.co/api/v2/pokemon/pikachu"
response = requests.get(url)

print(response.status_code)  # debe ser 200
print(response.json())

200

In [9]:
pokemons = []

for i in range(1, 200):  # primeros 200 Pokémon
    url = f"https://pokeapi.co/api/v2/pokemon/{i}"
    response = requests.get(url) # hacer la solicitud
    
    if response.status_code == 200:
        data = response.json()
        
        # extraer stats
        stats = {stat['stat']['name']: stat['base_stat'] for stat in data['stats']} # crear un diccionario de stats
        
        pokemons.append({ # crear un diccionario con la información relevante
            "name": data["name"],
            "type": data["types"][0]["type"]["name"],
            "height": data["height"],
            "weight": data["weight"],
            "attack": stats["attack"],
            "defense": stats["defense"],
            "speed": stats["speed"],
            "hp": stats["hp"]
        })

In [10]:
Hola_profe = pd.DataFrame(pokemons) # convertir la lista de diccionarios a un DataFrame

In [12]:
Hola_profe # FUNCIONAAA

           name     type  height  weight  attack  defense  speed  hp
0     bulbasaur    grass       7      69      49       49     45  45
1       ivysaur    grass      10     130      62       63     60  60
2      venusaur    grass      20    1000      82       83     80  80
3    charmander     fire       6      85      52       43     65  39
4    charmeleon     fire      11     190      64       58     80  58
..          ...      ...     ...     ...     ...      ...    ...  ..
194    quagsire    water      14     750      85       85     35  95
195      espeon  psychic       9     265      65       60    110  65
196     umbreon     dark      10     270      65      110     65  95
197     murkrow     dark       5      21      85       42     91  60
198    slowking    water      20     795      75       80     30  95

[199 rows x 8 columns]

In [15]:
Hola_profe.to_csv("pokemon_dataset.csv", index=False) # guardar el DataFrame como CSV (Gracias Chatgpt no sabia como)

## Ahora si Limpieza de datos

In [ ]:
Hola_profe.head() # mostrar las primeras filas del DataFrame para verificar que se cargó correctamente

         name   type  height  weight  attack  defense  speed  hp
0   bulbasaur  grass       7      69      49       49     45  45
1     ivysaur  grass      10     130      62       63     60  60
2    venusaur  grass      20    1000      82       83     80  80
3  charmander   fire       6      85      52       43     65  39
4  charmeleon   fire      11     190      64       58     80  58

In [ ]:
Hola_profe.info() # información general del DataFrame

<class 'pandas.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     199 non-null    str
 1   type     199 non-null    str
 2   height   199 non-null    int64
 3   weight   199 non-null    int64
 4   attack   199 non-null    int64
 5   defense  199 non-null    int64
 6   speed    199 non-null    int64
 7   hp       199 non-null    int64
dtypes: int64(6), str(2)
memory usage: 12.6 KB

In [21]:
Hola_profe.describe() # estadisticas descriptivas de las columnas numericas

           height       weight      attack     defense       speed          hp
count  199.000000   199.000000  199.000000  199.000000  199.000000  199.000000
mean    11.311558   406.904523   69.427136   66.326633   66.623116   64.603015
std      8.825091   541.306235   26.386281   26.360723   27.494970   27.104888
min      2.000000     1.000000    5.000000    5.000000   15.000000   10.000000
25%      6.000000    85.000000   50.000000   48.500000   45.000000   45.000000
50%     10.000000   265.000000   65.000000   65.000000   65.000000   60.000000
75%     14.000000   547.500000   87.500000   80.000000   88.500000   80.000000
max     88.000000  4600.000000  134.000000  180.000000  150.000000  250.000000

In [24]:
Hola_profe.isnull().sum() #No hay valores nulos, brutal

name       0
type       0
height     0
weight     0
attack     0
defense    0
speed      0
hp         0
dtype: int64

In [28]:
Hola_profe.sort_values("attack", ascending=False).head(1)

          name    type  height  weight  attack  defense  speed  hp
148  dragonite  dragon      22    2100     134       95     80  91

In [29]:
Hola_profe.sort_values("speed", ascending=False).head(1)

          name      type  height  weight  attack  defense  speed  hp
100  electrode  electric      12     666      50       70    150  60

Tenia curiosad